### PR TITLE
Apply UPM format to the repository

### LINKED ISSUE #2: Format as unity package
Hey @FreyaHolmer ! An awesome contribution! Perhaps You are open making this as a unity package ? If You do not know how - i can fork it and open as pull request :)

### PR DESCRIPTION
**Pull request by razenpok**
This PR:
- Moves all code into a `Runtime` folder. That's an unofficial guideline, which many of the packages stick to.
- Adds a `package.json` file with the required metadata (edit as you see fit)
- Adds UPM installation instructions to README
  - I took this opportunity to move the instructions to the top of the file, as that facilitates the package usage
  - The OpenUPM bit is forward-looking, I will send a publish request once this PR is merged
- Removes .gitignore and allows for `.meta` files. Unfortunately, this is required for Unity to work with UPM packages.

If you merge this PR, please make a `1.0.0` release on a **Releases** page, as OpenUPM pipelines work exclusively with git tags.

Closes #2

### CODE REVIEW

**Comment by FreyaHolmer** [comment]
thank you! although I might have to redo some of this on the dev branch, as dev is significantly further ahead than master at this point

**Comment by razenpok** [comment]
Oh, right, didn't see the dev branch. I can reproduce this PR on it, no biggie.

**Comment by razenpok** [comment]
By the way, is there any reason for the dev branch to be the main one? People who open https://github.com/FreyaHolmer/Mathfs end up being on master instead of dev, adding to the confusion (like in my case)

**Comment by FreyaHolmer** [comment]
the dev branch isn't stable because I'm actively working on it, but I could possibly make master the main branch once I have releases/tags in

**Pull request closed without merging**
