### PR TITLE
Apply UPM format to the repository 2:  Electric Boogaloo

### LINKED ISSUE #2: Format as unity package
Hey @FreyaHolmer ! An awesome contribution! Perhaps You are open making this as a unity package ? If You do not know how - i can fork it and open as pull request :)

### PR DESCRIPTION
**Pull request by razenpok**
'ight, let's try this again.

This PR:
- Moves all code into a `Runtime` and `Editor` folder. That's actually an [official guideline](https://docs.unity3d.com/Manual/cus-layout.html), which many of the packages stick to. This PR also fixes the paths in `MathfsCodegen` accordingly.
- Adds a `package.json` file with the required metadata (edit as you see fit) (now with Unity 2021.2+ requirement)
- Adds UPM installation instructions to README
  - I took this opportunity to move the instructions to the top of the file, as that facilitates the package usage
  - The OpenUPM bit is forward-looking, I will send a publish request once this PR is merged
- Removes `.gitignore` and allows for `.meta` files. Unfortunately, this is required for Unity to work with UPM packages.

If you merge this PR, please make a `1.0.0` release on a **Releases** page, as OpenUPM pipelines work exclusively with git tags.

Closes #2

### CODE REVIEW

**Comment by FreyaHolmer** [comment]
alright! just to make sure I got it right, and, a few things of note I guess

* I've been using com.acegikmo.shapes for my Shapes plugin, so I should use acegikmo for this too, but I presume I can just edit the manifest to match!
* I should make an (official) OpenUPM entry for this package (currently a fork is on there)
* There was a line ending change on Mathfs.cs, but, that just put it in line with the rest of the project so that was good! I presume no other changes were made in that file?
* I'm not quite ready for a stable 1.0.0 release yet. I'm not sure if I should public a 0.x.x version or if I should merge but hold off on the OpenUPM entry and tags until it's stable

**Comment by razenpok** [comment]
> I've been using com.acegikmo.shapes for my Shapes plugin, so I should use acegikmo for this too, but I presume I can just edit the manifest to match!

Yep, you can change it to whatever you like

> I should make an (official) OpenUPM entry for this package (currently a fork is on there)

Right, there's already a fork on OpenUPM. I think @favoyang (sorry mate for pinging you here and there) can help you with the transition

> There was a line ending change on Mathfs.cs, but, that just put it in line with the rest of the project so that was good! I presume no other changes were made in that file?

I don't think I've even touched it. Maybe that's git itself that changed the line endings? idk

> I'm not quite ready for a stable 1.0.0 release yet. I'm not sure if I should public a 0.x.x version or if I should merge but hold off on the OpenUPM entry and tags until it's stable

Same as with the package name, just stick to the semver and you are golden. You should also adjust the readme I guess.

**Comment by razenpok** [comment]
Regarding whether to publish or not: I think publishing 0.x.x is fine, as the 0.x.x releases are _expected_ to be non-stable.

**Comment by favoyang** [comment]
New openupm entry: https://openupm.com/packages/com.acegikmo.mathfs, with v0.1.0 published.

**Pull request merged**
